import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../models/subscription_model.dart';

/// Predefined catalog services available in Development Mode / Offline
final List<SubscriptionCatalogItem> mockCatalogList = [
  const SubscriptionCatalogItem(
    id: 'cat-1',
    name: 'Netflix',
    slug: 'netflix-standard',
    category: 'Streaming Video',
    tierName: 'Standard (HD)',
    defaultBillingCycle: 'monthly',
    priceTry: 229.99,
    priceUsd: 15.49,
    priceEur: 13.49,
    iconName: 'movie',
    isPopular: true,
  ),
  const SubscriptionCatalogItem(
    id: 'cat-2',
    name: 'Spotify',
    slug: 'spotify-individual',
    category: 'Music & Audio',
    tierName: 'Individual Premium',
    defaultBillingCycle: 'monthly',
    priceTry: 59.99,
    priceUsd: 11.99,
    priceEur: 10.99,
    iconName: 'music_note',
    isPopular: true,
  ),
  const SubscriptionCatalogItem(
    id: 'cat-3',
    name: 'YouTube Premium',
    slug: 'youtube-premium-individual',
    category: 'Music & Video',
    tierName: 'Individual',
    defaultBillingCycle: 'monthly',
    priceTry: 79.99,
    priceUsd: 13.99,
    priceEur: 12.99,
    iconName: 'smart_display',
    isPopular: true,
  ),
  const SubscriptionCatalogItem(
    id: 'cat-4',
    name: 'Exxen',
    slug: 'exxen-reklamsiz',
    category: 'Streaming Video',
    tierName: 'Ad-Free (Reklamsız)',
    defaultBillingCycle: 'monthly',
    priceTry: 222.50,
    priceUsd: 7.00,
    priceEur: 6.50,
    iconName: 'tv',
    isPopular: true,
  ),
  const SubscriptionCatalogItem(
    id: 'cat-5',
    name: 'BluTV',
    slug: 'blutv-standart',
    category: 'Streaming Video',
    tierName: 'Standard (Aylık)',
    defaultBillingCycle: 'monthly',
    priceTry: 139.90,
    priceUsd: 4.50,
    priceEur: 4.20,
    iconName: 'live_tv',
    isPopular: true,
  ),
  const SubscriptionCatalogItem(
    id: 'cat-6',
    name: 'ChatGPT Plus',
    slug: 'chatgpt-plus',
    category: 'AI & Productivity',
    tierName: 'Plus (GPT-4o)',
    defaultBillingCycle: 'monthly',
    priceTry: 649.99,
    priceUsd: 20.00,
    priceEur: 22.00,
    iconName: 'psychology',
    isPopular: true,
  ),
  const SubscriptionCatalogItem(
    id: 'cat-7',
    name: 'Amazon Prime',
    slug: 'amazon-prime-tr',
    category: 'Shopping & Video',
    tierName: 'Prime Membership',
    defaultBillingCycle: 'monthly',
    priceTry: 39.00,
    priceUsd: 14.99,
    priceEur: 8.99,
    iconName: 'local_shipping',
    isPopular: true,
  ),
  const SubscriptionCatalogItem(
    id: 'cat-8',
    name: 'Disney+',
    slug: 'disney-plus-standard',
    category: 'Streaming Video',
    tierName: 'Standard (Aylık)',
    defaultBillingCycle: 'monthly',
    priceTry: 164.90,
    priceUsd: 13.99,
    priceEur: 11.99,
    iconName: 'video_library',
    isPopular: true,
  ),
  const SubscriptionCatalogItem(
    id: 'cat-9',
    name: 'TOD (beIN Connect)',
    slug: 'tod-super-lig',
    category: 'Sports & TV',
    tierName: 'Süper Lig Paketi',
    defaultBillingCycle: 'monthly',
    priceTry: 389.00,
    priceUsd: 12.00,
    priceEur: 11.00,
    iconName: 'sports_soccer',
    isPopular: true,
  ),
  const SubscriptionCatalogItem(
    id: 'cat-10',
    name: 'Gain',
    slug: 'gain-premium',
    category: 'Streaming Video',
    tierName: 'Premium',
    defaultBillingCycle: 'monthly',
    priceTry: 149.00,
    priceUsd: 4.90,
    priceEur: 4.50,
    iconName: 'play_circle',
    isPopular: false,
  ),
  const SubscriptionCatalogItem(
    id: 'cat-11',
    name: 'iCloud+ (200GB)',
    slug: 'icloud-plus-200gb',
    category: 'Cloud Storage',
    tierName: '200 GB Tier',
    defaultBillingCycle: 'monthly',
    priceTry: 79.99,
    priceUsd: 2.99,
    priceEur: 2.99,
    iconName: 'cloud',
    isPopular: true,
  ),
  const SubscriptionCatalogItem(
    id: 'cat-12',
    name: 'Xbox Game Pass Ultimate',
    slug: 'xbox-game-pass-ultimate',
    category: 'Gaming',
    tierName: 'Ultimate',
    defaultBillingCycle: 'monthly',
    priceTry: 309.00,
    priceUsd: 19.99,
    priceEur: 17.99,
    iconName: 'sports_esports',
    isPopular: true,
  ),
  const SubscriptionCatalogItem(
    id: 'cat-13',
    name: 'Duolingo Super',
    slug: 'duolingo-super-individual',
    category: 'Education',
    tierName: 'Super Individual',
    defaultBillingCycle: 'monthly',
    priceTry: 129.99,
    priceUsd: 12.99,
    priceEur: 11.99,
    iconName: 'school',
    isPopular: false,
  ),
  const SubscriptionCatalogItem(
    id: 'cat-14',
    name: 'S Sport Plus',
    slug: 'ssport-plus-aylik',
    category: 'Sports & TV',
    tierName: 'Aylık Paket',
    defaultBillingCycle: 'monthly',
    priceTry: 99.99,
    priceUsd: 3.20,
    priceEur: 3.00,
    iconName: 'sports_basketball',
    isPopular: false,
  ),
  const SubscriptionCatalogItem(
    id: 'cat-15',
    name: 'Storytel',
    slug: 'storytel-unlimited',
    category: 'Audiobooks',
    tierName: 'Unlimited Audiobooks',
    defaultBillingCycle: 'monthly',
    priceTry: 149.99,
    priceUsd: 9.99,
    priceEur: 8.99,
    iconName: 'auto_stories',
    isPopular: false,
  ),
];

/// Catalog Provider
final catalogListProvider = Provider<List<SubscriptionCatalogItem>>((ref) {
  return mockCatalogList;
});
